name: Deploy

on: [push, pull_request, workflow_dispatch]

permissions: {}

env:
  FORCE_COLOR: 1
  HUGO_CACHEDIR: /tmp/hugo_cache

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0

      - name: Cache Hugo resources
        uses: actions/cache@v5
        with:
          path: |
            resources/_gen
            /tmp/hugo_cache
          key: hugo-${{ hashFiles('content/**', 'go.sum') }}
          restore-keys: |
            hugo-

      - name: Build
        run: pixi run hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
